[project]
name = "linux-hello"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "inspireface>=1.2.3.post5",
    "opencv-python>=4.13.0.90",
]
